[2025-03-15T17:26:07.418+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:26:03.626556+00:00 [queued]>
[2025-03-15T17:26:07.446+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:26:03.626556+00:00 [queued]>
[2025-03-15T17:26:07.447+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-15T17:26:07.533+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_data_task> on 2025-03-15 17:26:03.626556+00:00
[2025-03-15T17:26:07.541+0000] {standard_task_runner.py:60} INFO - Started process 104456 to run task
[2025-03-15T17:26:07.545+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'insert_data_task', 'manual__2025-03-15T17:26:03.626556+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpu99t5nc2']
[2025-03-15T17:26:07.555+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask insert_data_task
[2025-03-15T17:26:07.754+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.insert_data_task manual__2025-03-15T17:26:03.626556+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-15T17:26:07.999+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='insert_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T17:26:03.626556+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T17:26:03.626556+00:00'
[2025-03-15T17:26:08.035+0000] {logging_mixin.py:188} INFO - ❌ Erreur lors de l'insertion des données : set_session cannot be used inside a transaction
[2025-03-15T17:26:08.036+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-15T17:26:08.069+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Google_map, task_id=insert_data_task, execution_date=20250315T172603, start_date=20250315T172607, end_date=20250315T172608
[2025-03-15T17:26:08.136+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-15T17:26:08.180+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
