[2025-03-16T18:27:45.909+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T18:22:09.744491+00:00 [queued]>
[2025-03-16T18:27:45.960+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T18:22:09.744491+00:00 [queued]>
[2025-03-16T18:27:45.960+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2025-03-16T18:27:46.002+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_phase_2_task> on 2025-03-16 18:22:09.744491+00:00
[2025-03-16T18:27:46.014+0000] {standard_task_runner.py:60} INFO - Started process 176603 to run task
[2025-03-16T18:27:46.022+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'transform_phase_2_task', 'manual__2025-03-16T18:22:09.744491+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpxwhqonkw']
[2025-03-16T18:27:46.027+0000] {standard_task_runner.py:88} INFO - Job 140: Subtask transform_phase_2_task
[2025-03-16T18:27:46.207+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.transform_phase_2_task manual__2025-03-16T18:22:09.744491+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-16T18:27:46.470+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='transform_phase_2_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T18:22:09.744491+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T18:22:09.744491+00:00'
[2025-03-16T18:27:57.045+0000] {logging_mixin.py:188} WARNING - [nltk_data] Downloading package stopwords to /home/nord/nltk_data...
[2025-03-16T18:27:57.047+0000] {logging_mixin.py:188} WARNING - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-16T18:27:57.048+0000] {logging_mixin.py:188} WARNING - [nltk_data] Downloading package punkt_tab to /home/nord/nltk_data...
[2025-03-16T18:28:00.225+0000] {logging_mixin.py:188} WARNING - [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[2025-03-16T18:28:05.269+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/nord/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nord/airflow/dags/google_map_dag_etl.py", line 51, in <lambda>
    python_callable=lambda: __import__('transform_phase_2').main()
  File "/home/nord/airflow/dags/transform_phase_2.py", line 84, in main
  File "/home/nord/airflow/dags/transform_phase_2.py", line 54, in extract_common_topics
    corpus = [dictionary.doc2bow(text) for text in preprocessed_reviews]
NameError: name 'gensim' is not defined
[2025-03-16T18:28:05.294+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Google_map, task_id=transform_phase_2_task, execution_date=20250316T182209, start_date=20250316T182745, end_date=20250316T182805
[2025-03-16T18:28:05.314+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 140 for task transform_phase_2_task (name 'gensim' is not defined; 176603)
[2025-03-16T18:28:05.423+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-16T18:28:05.462+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
