[2025-03-17T12:26:41.405+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Google_map.load_phase_2_task manual__2025-03-17T12:26:35.237641+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
