[2025-03-03T15:31:28.177+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Simple_etl.file_sensor manual__2025-03-03T15:31:17.079223+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
