[2025-03-17T16:00:24.327+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Google_map.transform_phase_2_task manual__2025-03-17T16:00:16.684567+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
